name: MobWars
description: The minigame plugin where your mobs fight other mobs!
version: b1.1.5
author: NathanApes

main: nathan.apes.mw.main.MobWars

commands: 
  
  defaultcmd: 
    description: Just a default.
    usage: /defaultcmd
    